### PR TITLE
#37 node-gyp@5.0.2

### PR DESCRIPTION
**Pull request by irega**
Bumps node-gyp from ^4.0.0 to ^5.0.2. We need this update due to adding Visual Studio 2019 support and to syncs the version with the included in npm:
[https://github.com/npm/cli/pull/208](https://github.com/npm/cli/pull/208)

Thank you!

### CODE REVIEW

**Comment by irega** [comment]
@isaacs tests are failing due to the tap version changed in this [commit](https://github.com/npm/npm-lifecycle/commit/dbbfe27804b385a482b1dc369be6b6ce34e97c80). It seems with the last tap versions they break the compatibility with nodejs v6. Let me know if I should change something more in the PR. Thank you!

**Comment by isaacs** [comment]
Can you pull the latest branch and try this again?  I rolled back the tap updates.  Indeed, "they" break compatibility with node 6, so it'll have to wait for this module's next semver-major bump.

<details>
The joke is that I'm the node-tap team. ;P
</details>

**Comment by irega** [comment]
Now it passed tests successfully, thank you @isaacs ! Should I register a new issue in the "node-tap" GitHub repository to fix the nodejs 6 compatibility or you can merge this PR (and publish the new package version)?

**Comment by isaacs** [comment]
I have a feeling the node-tap team would close that issue as "wontfix".  Node 6 is past its LTS expiration date.  npm v7 won't support it either.

I'll most likely get this in for npm 6.10.1 or 6.10.2.

**Comment by ljharb** [comment]
Wouldn't that mean that npm 6 would stop working on node 6 in a non-major release?

**Comment by isaacs** [comment]
Oh, does node-gyp v5 drop support for Node v6?  If so, yes, we'd have to put this off until npm 7.

**Comment by isaacs** [comment]
@ljharb It looks like node-gyp 5 is [passing tests on Node v6](https://github.com/nodejs/node-gyp/runs/165029825), so this should probably be fine.

I was saying that I won't be updating tap to v14 (here or in npm/cli) until npm v7, because it drops node v6 support.  So, it'll be in a semver major bump.

**Comment by ljharb** [comment]
Awesome, that was just my confusion then - thanks for clarifying.

**Comment by irega** [comment]
> I have a feeling the node-tap team would close that issue as "wontfix". Node 6 is past its LTS expiration date. npm v7 won't support it either.
> 
> I'll most likely get this in for npm 6.10.1 or 6.10.2.

Your feelings are correct 😆 I totally agree. Waiting for the new "npm-lifecycle" version to continue with the npm PR, then. Thank you!

**Pull request closed without merging**
